name: Create Archive
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: montudor/action-zip@v1
      with:
       args: zip -qq index.zip index.html
